master: 
  host: 10.104.64.86
  port: 3306
  username: ivenet1
  password: dlwodbs0303
  database: unpobby1_godomall_com
slave1:
  host: 10.104.64.86
  port: 3306
  username: ivenet1
  password: dlwodbs0303
  database: unpobby1_godomall_com
